added isolate service example
grpc/grpc-dart pull request #255
Opened 2019-12-04 21:30 UTC by DisDis

2019-12-04 21:31 UTC, DisDis commented
@sigurdm ping

2019-12-09 21:45 UTC, DisDis commented
@sigurdm ping

2020-08-24 18:33 UTC, bordunosp commented
ping

2020-09-24 10:47 UTC, mraleph requested changes

2020-09-24 10:47 UTC, mraleph commented on example/isolate-service/README.md
> +# Description
This seems to be copied verbatim from the hello world folder and needs some updates, e.g. you can explain that this is an example of load balancing using multiple isolates listening to the same socket which is made possible by passing `shared: true` to `Server.serve`. 

I would also rename the folder from `isolate-service` to `helloworld-with-isolates`.

2020-09-24 10:47 UTC, mraleph commented on example/isolate-service/bin/server.dart
> +Future _sendStop(SendPort stopPort) => singleResponseFuture(stopPort.send);
It's unclear why this is a separate function. Can't it be folded into caller?

2020-09-24 10:47 UTC, mraleph commented on example/isolate-service/bin/server.dart
> +    _log.info('Service shutdowning...');
`Service shutting down`

2020-10-26 14:54 UTC, mit-mit commented
@DisDis sorry for the (long) initial delay on review here. Are you still interested in working on this one?

2020-10-28 14:03 UTC, mraleph commented
Closing as assumed stale for now.

2020-10-28 14:03 UTC, closed without merging