Pass service to interceptors
grpc/grpc-dart pull request #272
Opened 2020-01-22 16:39 UTC by jey

A single `grpc.Server` can have multiple services, so interceptors may need to know which service they're acting on. Just having the method and its name is insufficient.

2020-01-22 17:17 UTC, jey commented
Actually, shouldn't the interceptor be responsible for invoking the underlying method too? That's how it works go-grpc's [UnaryServerInterceptor](https://godoc.org/google.golang.org/grpc#UnaryServerInterceptor).

This would allow many additional uses of interceptors: method timing, error logging, etc

2020-09-24 10:23 UTC, mraleph requested changes
Thanks for your contribution and apologies for the delay in review.

See suggestions below. Additionally this needs at least some tests which access `service` and verify that it's correct.

2020-09-24 10:23 UTC, mraleph commented on pubspec.yaml
> -version: 2.1.3
This would need a CHANGELOG.md entry describing the change.

2020-09-24 10:23 UTC, mraleph commented on lib/src/server/interceptor.dart
> +    ServiceCall call, Service service, ServiceMethod method);
What about just exposing this information through `ServiceCall`, e.g. you can add

```dart
class ServiceCall {
  /// ...
  Service get service;
  
  /// ...
  ServiceMethod get method;
}
```

Then you can access this information through `call` and you would not need to make a breaking change to `Interceptor` signature.

2020-09-24 10:24 UTC, mraleph commented
> Actually, shouldn't the interceptor be responsible for invoking the underlying method too? That's how it works go-grpc's [UnaryServerInterceptor](https://godoc.org/google.golang.org/grpc#UnaryServerInterceptor).
> 
> This would allow many additional uses of interceptors: method timing, error logging, etc

Yeah, I noticed the discrepancy between how interceptors work in Dart and other implementations. 

If you are still interested in refactoring that feel free to submit a separate PR for that.

2020-10-25 13:17 UTC, shaxbee commented
> > Actually, shouldn't the interceptor be responsible for invoking the underlying method too? That's how it works go-grpc's [UnaryServerInterceptor](https://godoc.org/google.golang.org/grpc#UnaryServerInterc
> If you are still interested in refactoring that feel free to submit a separate PR for that.

@mraleph I'm happy to refractor using similar interface to ClientInterceptor.

2020-10-28 14:08 UTC, mraleph commented
> @mraleph I'm happy to refractor using similar interface to `ClientInterceptor`.

This would be breaking change - so there should be either strong demand for it or it should be clear that not so many users even use interceptors. It is unclear if either is true for interceptors. 

If you would like to submit refactoring maybe we could first _add_ another interceptor mechanism which is more aligned with other implementations and mark current interceptor mechanism deprecated. Then we can remove current interceptor mechanism at a later date after few releases.

2020-10-28 14:08 UTC, mraleph commented
@jey if you are still interested in landing this PR let me know. For now I am going to close it as stale.

2020-10-28 14:08 UTC, closed without merging