Support for http based grpc-web for mobile
grpc/grpc-dart pull request #557
Opened 2022-06-03 14:56 UTC by otakuto

https://github.com/grpc/grpc-dart/pull/287
https://github.com/grpc/grpc-dart/pull/351
This will be a re-attempting of the above.

Best regards for your review.

2022-06-06 19:33 UTC, devoncarew commented
@sigurdm @mraleph - who would be best to review this?

2022-06-07 07:02 UTC, mraleph commented
@otakuto thanks for taking your time to contribute. Could you try to fix EasyCLA check? We can't look at the code before it is fixed.

2022-06-08 07:54 UTC, mraleph commented
@otakuto Could you outline a specific use case which makes you interested in using gRPC-Web from a mobile application? Any specific reason that prevents you from using the native gRPC protocol instead?

/cc @wenbozhu

2022-06-09 02:56 UTC, otakuto commented
> @otakuto thanks for taking your time to contribute. Could you try to fix EasyCLA check? We can't look at the code before it is fixed.

I fixed it.

2022-06-09 02:57 UTC, otakuto commented
> @otakuto Could you outline a specific use case which makes you interested in using gRPC-Web from a mobile application? Any specific reason that prevents you from using the native gRPC protocol instead?
> 
> /cc @wenbozhu

In this example, there is a reason why it is difficult for a microcontroller to support HTTP2 when communicating with a microcontroller such as ESP32 and mobile, for example.
Another advantage is that it is possible to implement a pure dart client for mobile and web respectively.

2022-06-09 07:14 UTC, mraleph commented
@otakuto 

> In this example, there is a reason why it is difficult for a microcontroller to support HTTP2 when communicating with a microcontroller such as ESP32 and mobile.

Makes sense. HTTP2 stack might be quite large so it does not necessarily fit on a microcontroller. 

> Another advantage is that it is possible to implement a pure dart client for mobile and web respectively.

Could you elaborate what you mean by this?

One of the problems with merging this (and officially supporting gRPC-Web protocol on native targets) is that it would block us from migrating our gRPC-Web implementation to use official JavaScript implementation underneath, which is something that we have been considering to reduce our maintenance burden.

2023-04-13 09:20 UTC, johynpapin commented
Hello !

I want to share another use case for this feature.

As written in #216, another use case is to be able to use the gRPC-Web protocol to bypass the limitations of some cloud platforms, such as DigitalOcean's App Platform service which does not allow to expose a gRPC service.

2023-04-15 12:09 UTC, mreimer commented
I'd like to add another vote in support of this PR. AWS lambda doesn't support HTTP2, and while I'm not familiar with other FaaS environments I expect lambda isn't the only one with this constraint. I appreciate the need to control your maintenance surface area but I think it would be a shame to commit to never supporting grpc-web on native targets.

For what it's worth I've locally rebased this PR on 3.1.0 and tested it for my use case, LGTM.

2023-05-03 08:42 UTC, johynpapin commented
Hello !

We have tested these changes on our API and everything seems OK on our side too.

Maybe another solution would be to export what is needed to be able to offer this functionality in another package?

2023-08-21 12:11 UTC, mosuem requested changes
Thanks for the contribution! Tests are missing and a few smaller comments.

2023-08-21 12:11 UTC, mosuem commented on lib/src/client/transport/http_transport.dart
> +  HTTPTransportStream(client, request,
The arguments should be typed.

2023-08-21 12:11 UTC, mosuem commented on lib/src/client/transport/http_transport.dart
> +class HTTPTransportStream implements GrpcTransportStream {
Rename this and similar to ``Http...` for consistency.

2023-08-21 12:11 UTC, mosuem commented on lib/src/client/transport/http_transport.dart
> +class HTTPClientConnection extends ClientConnection {
Why `extend` and not `implement`?

2023-08-21 12:11 UTC, mosuem commented on lib/src/client/transport/http_transport.dart
> +    }
Should the other headers also be set as in the `XhrClientConnection`?

2023-08-21 12:11 UTC, mosuem commented on lib/src/client/transport/http_transport.dart
> +        _onError(GrpcError.unavailable('HTTPConnection connection-error'),
See above, also `Http`

2024-08-09 08:13 UTC, mosuem commented
Closing as this has been waiting for changes for a long time.

2024-08-09 08:13 UTC, closed without merging