Bump http version from 0.13.0 to 1.0.0
grpc/grpc-dart pull request #629
Opened 2023-05-24 05:56 UTC by ghatdev

2023-05-24 15:54 UTC, kevmoo commented
@domesticmouse – we should have CI set to the oldest supported SDK

2023-05-24 15:54 UTC, kevmoo commented
We should have a WIDE constraint on pkg:http – there were no breaks AFAIK

2023-05-30 21:46 UTC, kevmoo commented on pubspec.yaml
> +  http: ^1.0.0
```suggestion
  http: '>=0.13.0 <2.0.0.'
```

2023-05-31 05:52 UTC, kevmoo commented on pubspec.yaml
> +  http: '>=0.13.0 <2.0.0.'
```suggestion
  http: '>=0.13.0 <2.0.0'
```

2023-05-31 19:16 UTC, kevmoo requested changes
One change - for the changelog, please!

2023-05-31 19:16 UTC, kevmoo commented on pubspec.yaml
> +  http: '>=0.13.0 <2.0.0'
We should add an entry in the changelog for v3.2.0-dev about this as well!

2023-06-01 06:23 UTC, ghatdev commented
@kevmoo Is this will be O.K?

2023-06-15 16:40 UTC, kevmoo commented on pubspec.yaml
> +  http: '>=0.13.0 <2.0.0'
Add an entry to the `changelog` file that mentions this change.

2023-06-15 23:15 UTC, domesticmouse commented
> @kevmoo Is this will be O.K?

Please update the [CHANGELOG.md](https://github.com/grpc/grpc-dart/blob/master/CHANGELOG.md) file to mention this change. You can use `NEXT` as the version that will include the change.

2023-06-16 00:36 UTC, kevmoo approved these changes

2023-06-16 00:59 UTC, domesticmouse commented
Oh wait, it looks like the CI on this repo is set to publish on commit, and really doesn't like the version `NEXT` in the change log. 

@kevmoo any preference on what the new version should be?

2023-06-16 01:01 UTC, kevmoo commented
`3.2.1` is great!

2023-06-16 01:33 UTC, ghatdev commented
@kevmoo @domesticmouse I just set the version to 3.2.1

2023-06-16 01:44 UTC, domesticmouse approved these changes

2023-06-16 21:18 UTC, merged

2023-06-17 02:03 UTC, domesticmouse commented
@kevmoo any idea how to get this published?

2023-06-17 05:12 UTC, kevmoo commented
I have the keys!

2023-06-19 08:50 UTC, mraleph commented
@kevmoo you forgot to create a release... also there is a publishing workflow through actions (https://github.com/grpc/grpc-dart/blob/master/.github/workflows/publish.yaml) so you don't need to manually publish.

2023-06-19 14:29 UTC, kevmoo commented
I don't have admin access to this repo – so the publish action was broken for me.