Update on http package  from 0.13.0 to 1.0.0
grpc/grpc-dart pull request #635
Opened 2023-06-11 15:30 UTC by Emmanuelfrimpong

2023-06-12 03:30 UTC, domesticmouse commented
@Emmanuelfrimpong please sign the CLA. We can't land this PR without the CLA signed. Thanks!

2023-06-12 22:48 UTC, kevmoo commented on pubspec.yaml
> +  http: ^1.0.0
We want a wide range here to support migration!

```suggestion
  http: '>=0.13.0 <2.0.0'
```

2023-06-12 22:48 UTC, kevmoo requested changes
Also please add a changelog entry!

2023-06-21 20:11 UTC, devoncarew commented
Looks like the equivalent change landed in https://github.com/grpc/grpc-dart/pull/629.

2023-06-21 20:12 UTC, closed without merging